### ISSUE TITLE
Release to npm

### ISSUE THREAD

**Issue by havenchyk** [pukhalski/tap#24]
Hi Ilya,

Npm can be used to handle frontend dependencies without bower. Could you release tap.js to npm?

**Comment by yoyurec** [comment]
read NPM docs!
`npm install pukhalski/tap --save` :100:

**Comment by havenchyk** [comment]
@yoyurec thanks for tip, I will.

**Comment by iamstarkov** [comment]
@pukhalski can you help us?

**Comment by havenchyk** [comment]
@pukhalski is there any plans to do it?

**Comment by larchanka** [comment]
@havenchyk @iamstarkov 
we plan to do it really soon

**Comment by iamstarkov** [comment]
this week or month?

**Comment by pukhalski** [comment]
@iamstarkov, week. But not sure how to deal with React support for tap. It's still in a process of investigation.

**Comment by iamstarkov** [comment]
@pukhalski take a look on "react-tap-event-plugin" implementation — it’s a bit complicated inside, because it have to deal with synthetic event system — but it seems to be me as reasonable way to create new events in reactjs land. Also, it’s simplest and the best solution, we can choose from Hammer and fastclick solutions http://stackoverflow.com/q/24335821/1057730.

**Comment by pukhalski** [comment]
Hey guys, it seems that the name Tap is already taken. Any thoughts on how to name the package?

I am a bit disappointed that bower and npm packages would have different namings...

cc/ @iamstarkov, @larchanka, @havenchyk

**Comment by pukhalski** [comment]
Released as [tapjs](https://www.npmjs.com/package/tapjs). Grab it!

**Comment by havenchyk** [comment]
Cool, thanks. As for `tap` - it's well known test library. Tapjs look good to me.

**Comment by iamstarkov** [comment]
Great

**Comment by iamstarkov** [comment]
:+1: :tada:
